name: Upload Python Package
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt
        pip install bandit
        pip install flake8
        pip install pylint
    - name: bandit
      run:
        bandit -r ${{ env.working-directory }}
    - name: flake8
      run: flake8 ${{ env.working-directory }}
    - name: pylint
      run: pylint ${{ env.working-directory }} --load-plugins=pylint.extensions.bad_builtin
